mysql:
    build: images/macmysql
    restart: always
    volumes:
        - $PWD/data/mysql:/var/lib/mysql:rw
        - $PWD/conf/mysql:/etc/mysql/conf.d:ro
    user: mysql
    expose:
        - "3306"
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=mytest
        - MYSQL_USER=mytest
        - MYSQL_PASSWORD=mytest123
redis:
    image: redis
    restart: always
    volumes:
        - ./data/redis:/data
        - ./conf/redis/redis.conf:/etc/redis.conf
    expose:
        - "6379"
    command: redis-server /etc/redis.conf
