pyramid:
    build: images/pyramid
    restart: on-failure:10
    volumes:
        - ./source:/source
        - ./log:/log
        - ./conf/supervisor:/etc/supervisor/conf.d
    ports:
        - "8888:6543"
    links:
        - redis
        - mysql
mysql:
    build: images/macmysql
    restart: always
    volumes:
        - ./data/mysql:/var/lib/mysql:rw
        - ./conf/mysql:/etc/mysql/conf.d:ro
    expose:
        - "3306"
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=mytest
        - MYSQL_USER=mytest
        - MYSQL_PASSWORD=mytest123
redis:
    image: redis
    restart: always
    volumes:
        - ./data/redis:/data
        - ./conf/redis/redis.conf:/etc/redis.conf
    expose:
        - "6379"
    command: redis-server /etc/redis.conf
